version: '3.1'
services:
  teamspeak:
    image: kleberbaum/docker-teamspeak-new:gina
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: example
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
      WP_BACKUP_GIT_REPO: https://bitbucket.org/kleberbaum/ts3_party_backup.git
      WP_BACKUP_GIT_USER: kleberbaum
      WP_BACKUP_GIT_PASSWD: Utilman3295
      WP_BACKUP_INTERVAL: weekly
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: teamspeak
